version: "3.7"
services:

  dev-cards:
    image: localhost/dev-cards
    restart: unless-stopped
    user: "${UID_GID:-1000:1000}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID_GID: "${UID_GID:-1000:1000}"
    volumes:
      - dev_cards_data:/home/node
      - .:/app
      - /app/.git
    ports:
      - 3000:3000

volumes:
  dev_cards_data:
