version: "3.7"
services:

  cards-develop:
    image: localhost/cards-develop
    user: "${UID_GID:-1000:1000}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID_GID: "${UID_GID:-1000:1000}"
    volumes:
      - home_data:/home/node
      - .:/app
      - /app/.git
    ports:
      - 3000:3000

volumes:
  home_data:
