version: "3.7"
services:

  cards-develop:
    image: cards-develop
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    volumes:
      - node_modules_data:/home/node/node_modules
      - local_data:/home/node/local
      - .:/home/node/app
    ports:
      - 3000:3000


volumes:
  node_modules_data:
  local_data:
