export const threshold = 5000;
export const thresholdText = " after 5 seconds.";
export const baseURL = "http://localhost:3000";
export const createRoute = "/create";
export const learnRoute = "/learn";
export const cardsetRoute = "/cardset";
export const learnBoxRoute = "/box";
export const superMemoRoute = "/memo";
export const poolRoute = "/pool";
