version: "3.7"
services:

  mongodb:
    image: mongo:latest
    volumes:
      - "data:/data/db"

  app:
    image: arsnova/arsnova-cards
    build:
      context: ./app
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://@mongodb:27017/meteor
      - ROOT_URL=http://localhost:3000

  proxy:
    image: arsnova/arsnova-cards-proxy
    build: ./proxy
    ports:
      - "8080:80"
    depends_on:
      - app
