version: "3.7"
services:

  mongodb:
    image: arsnova/linux-cards-db
    volumes:
      - "data:/data/db"

  cards:
    image: arsnova/linux-cards:master
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/meteor
      - ROOT_URL=http://localhost:3000
    ports:
      - 3000:3000

volumes:
  data:
    driver: local
