@startuml

skinparam class {
	BackgroundColor palegreen
	BorderColor darkgray
	ArrowColor black
	FontSize 12
	BackgroundColor<<USP>> Wheat
    BorderColor<<USP>> Tomato
}

skinparam linetype ortho
skinparam shadowing true
skinparam minClassWidth 150
skinparam LegendBackgroundColor LightCyan
skinparam LegendBorderThickness 0
skinparam LegendFontName Helvetica
skinparam LegendFontSize 12

hide methods
hide circle

package "arsnova.cards | domain diagram" <<Frame>>{

class CardIndex <<USP>> {
	title
	description
	type
	level
	access
	license
}

together {
    class Transcript
    class TranscriptCoupledWithLecture  <<USP>> {
        lectureDates
    }
}

class Card {
	title
	sides
	content
	learningObjective
}
class TopicPool
class Repetitorium {
    title
    description
    access
    }

together {
    class LearningLoad {
        dailyNumberOfCards
    }
    class LearningStrategy {
        start
        end
    }
    class WozniakAlgorithm
    class LeitnerAlgorithm
    class PomodoroTimer <<USP>> {
        number of Pomodori
    }
    class LearningStatus {
        statistics
    }
    class Bonus <<USP>> {
        bonusPoints
        bonusRegister
    }
    class LearningBonus  <<USP>>
    class Transcript  <<USP>> {
        access
    }
    class TranscriptBonus  <<USP>> {
        minimumNumberOfTranscripts
    }
}

together {
    TopicPool o---right- Repetitorium
}

TopicCloud -down- TopicPool: : visualizes >
Repetitorium  o---left- "*" CardIndex
Card "*" -left-* "1" CardIndex
note bottom: There will be about 20 study-specific \ncard-index types, e. g.:\n\n - learning unit\n - commands set \n - formula collection\n - design patterns\n - exam questions\n - quotations\n - subject bibliography\n - vocabulary\n
CardIndex -down--o TopicPool

Transcript -right-|> Card
TranscriptCoupledWithLecture -down-|> Transcript
LearningStatus -right- LearningLoad: visualizes >
LearningLoad -up- LearningStrategy
LearningStrategy -up- PomodoroTimer
WozniakAlgorithm -up-|> LearningStrategy
LeitnerAlgorithm -up-|> LearningStrategy
LearningLoad -up- LearningBonus
LearningBonus -left-|> Bonus
TranscriptBonus -down-|> Bonus
TranscriptCoupledWithLecture -left- TranscriptBonus

}

legend right
  |= <img:https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/whatsapp/186/tomato_1f345.png> |= \n [[https://arsnova.cards arsnova.cards]] \n\n Technische Hochschule Mittelhessen – THM \n University of Applied Sciences |
  | Projekt-Website | [[https://arsnova.thm.de]] |
  | Repository | [[https://git.thm.de/cards]] |
  | Staging Server | [[https://staging.arsnova.cards]] |
  | RUP-Phase| Inception|
  | UML-Tool| PlantUML v. 1.2019.6|
  | Modellversion| v.1.1 |
  | Erstelldatum| 29.05.2019 |
  | Ersteller| Sergej Lopatin|
  | E-Mail| sergej.lopatin@mni.thm.de |
  | Letzte Änderung| 31.05.2019 |
  | Letzter Bearbeiter| Dr. Klaus Quibeldey-Cirkel |
  | E-Mail| klaus.quibeldey-cirkeln@mni.thm.de |
end legend

@enduml